"""SpecWiz CLI application."""

import sys
from pathlib import Path

import typer
from rich.console import Console

from specwiz.cli.commands.generate import generate_app
from specwiz.cli.commands.rulebook import rulebook_app

# Create CLI app
app = typer.Typer(
    name="specwiz",
    help="Documentation generation platform with versioned rulebooks",
    no_args_is_help=True,
)

# Create console for output
console = Console()

# Add command groups
app.add_typer(
    generate_app, name="generate", help="Generate documents (PRD, user guide, release notes)"
)
app.add_typer(rulebook_app, name="rulebook", help="Manage documentation rulebooks")


@app.command()
def init(
    product: str = typer.Option(..., help="Product name"),
    repo: str = typer.Option(default=".", help="Path to product repository"),
    output: str = typer.Option(default=".specwiz", help="Output directory for generated artifacts"),
) -> None:
    """Initialize a new SpecWiz project."""
    from rich.panel import Panel

    try:
        repo_path = Path(repo).resolve()
        output_path = Path(output).resolve()

        if not repo_path.exists():
            console.print(f"[red]Error: Repository path not found: {repo_path}[/red]")
            sys.exit(1)

        # Create output directory
        output_path.mkdir(parents=True, exist_ok=True)

        # Create basic config file
        config_content = f"""# SpecWiz Configuration
# Generated by: specwiz init

project_name: {product}
project_root: {repo_path}
storage_path: {output_path}
llm_model: claude-3-opus-20240229
llm_provider: anthropic
"""
        config_file = repo_path / "specwiz.yaml"
        config_file.write_text(config_content)

        console.print(
            Panel(
                f"[green]✓ Project initialized![/green]\n"
                f"Product: [bold]{product}[/bold]\n"
                f"Repository: {repo_path}\n"
                f"Output: {output_path}\n"
                f"Config: {config_file}",
                title="SpecWiz Init",
                expand=False,
            )
        )

    except Exception as e:
        console.print(f"[red]Error: {e}[/red]")
        sys.exit(1)


@app.command()
def doctor() -> None:
    """Check SpecWiz system health and configuration."""
    from rich.table import Table

    from specwiz.adapters import BlinkerEventBusAdapter, LocalStorageAdapter
    from specwiz.core.managers import CompositeConfigAdapter

    table = Table(title="SpecWiz System Health Check")
    table.add_column("Component", style="cyan")
    table.add_column("Status", style="magenta")
    table.add_column("Details", style="green")

    # Check Python version
    py_version = f"{sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}"
    table.add_row("Python", "✓", f"v{py_version}")

    # Check config
    try:
        config = CompositeConfigAdapter()
        errors = config.validate()
        if errors:
            table.add_row("Configuration", "⚠", f"{len(errors)} issues")
            for error in errors:
                table.add_row("  ", "", f"  • {error}")
        else:
            table.add_row("Configuration", "✓", "Valid")
    except Exception as e:
        table.add_row("Configuration", "✗", f"Error: {e}")

    # Check API connectivity
    try:
        import os

        if os.getenv("ANTHROPIC_API_KEY"):
            table.add_row("Anthropic API", "✓", "Key configured")
        else:
            table.add_row("Anthropic API", "⚠", "Key not set (ANTHROPIC_API_KEY)")
    except Exception as e:
        table.add_row("Anthropic API", "✗", str(e))

    # Check adapters
    try:
        LocalStorageAdapter()
        table.add_row("Storage Adapter", "✓", "LocalStorageAdapter ready")
    except Exception as e:
        table.add_row("Storage Adapter", "✗", str(e))

    try:
        BlinkerEventBusAdapter()
        table.add_row("Event Bus", "✓", "BlinkerEventBusAdapter ready")
    except Exception as e:
        table.add_row("Event Bus", "✗", str(e))

    console.print(table)


@app.callback(invoke_without_command=True)
def version_callback(
    version: bool = typer.Option(
        None,
        "--version",
        help="Show version information",
    ),
) -> None:
    """Display version information."""
    if version:
        from specwiz import __version__

        console.print(f"SpecWiz v{__version__}")
        raise typer.Exit(code=0)


def main() -> None:
    """Main entry point."""
    app()


if __name__ == "__main__":
    main()
